name: 'Complete release'
description: 'Complete release'
inputs:
  github-token:  # id of input
    description: 'Github api token if you want to fetch private repo'
    required: true
    default: null
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'lib/index.js'